// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function GetListOfFiles() {
  return window['go']['main']['App']['GetListOfFiles']();
}

export function SaveContent(arg1, arg2) {
  return window['go']['main']['App']['SaveContent'](arg1, arg2);
}
