// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote(arg1:string):Promise<void>;

export function GetListOfFiles():Promise<Array<main.MarkdownFile>>;

export function SaveContent(arg1:string,arg2:string):Promise<void>;
